name: CI

on: [push, pull_request]

jobs:
  Lint-Format-Checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pydocstyle
        pip install .
        python3 -c "import electricpy; print('electricpy.__file__')"
    - name: Test NumpyDoc Style
      run: |
        cd electricpy
        pydocstyle --convention=numpy
    - name: Test Black Code Format
      run: |
        pip install black
        black --check .